language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
jobs:
  include:
    # - stage: build base image
    #   script:
    #     - docker --version # print the version for logging
    #     - docker build -t nodebaseimage udagram-api/base_image/
    #     - docker tag nodebaseimage eedy/nodebaseimage:v1
    #   after_success:
    #     - echo "$DOCKERUB_TOKEN" | docker login --username "$DOCKER_NAME" --password-stdin
    #     - docker push eedy/nodebaseimage:v1

    - stage: build backend-api
      script:
        - docker build -f udagram-api/backend_users/Dockerfile -t backendapiusersimage
        - docker build -f udagram-api/backend_feed/Dockerfile -t backendapifeedimage
        - docker tag backendapifeedimage eedy/backendapifeedimage:v1
        - docker tag backendapiusersimage eedy/backendapiusersimage:v1
      after_success:
        - echo "$DOCKERUB_TOKEN" | docker login --username "$DOCKER_NAME" --password-stdin
        - docker push eedy/backendapifeedimage:v1
        - docker push eedy/backendapiusersimage:v1

    - stage: build reverse-proxy
      language: bash 
      script:
        - docker build -f reverse_proxy/Dockerfile -t reverseproxy
        - docker tag reverseproxy eedy/reverseproxy:v1
      after_success:
        - echo "$DOCKERUB_TOKEN" | docker login -u "$DOCKER_NAME" --password-stdin
        - docker push eedy/reverseproxy:v1
    
    - stage: build frontend image
      script:
        - docker build -f udagram-frontend/Dockerfile -t frontend
        - docker tag frontend eedy/frontend:latest
      after_success:
        - echo "$DOCKERUB_TOKEN" | docker login -u "$DOCKER_NAME" --password-stdin
        - docker push eedy/frontend:latest 