apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-users-api
  labels:
    service: udagram-backend-users-api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-backend-users-api
  type: ClusterIP