apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-backend-feed-api
  labels:
    app: udagram-backend-feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-backend-feed-api
  template:
    metadata:
      labels:
        app: udagram-backend-feed-api
    spec:
      containers:
      - name: udagram-backend-feed-api
        image: eedy/backendapifeedimage:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: environ
            mountPath: "/etc/environ"
            readOnly: true
      volumes:
        - name: environ
          configMap:
            name: env-variable