apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-feed-api
  labels:
    service: udagram-backend-feed-api
spec:
  ports:
  - name: http
  - port: 8080
    targetPort: 8080
  selector:
    app: udagram-backend-feed-api