apiVersion: v1
kind: Service
metadata:
  name: udagram-backend-feed-api
  labels:
    run: udagram-backend-feed-api
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: udagram-backend-feed-api