apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-api
  labels:
    app: udagram-frontend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend-api
  template:
    metadata:
      labels:
        app: udagram-frontend-api
    spec:
      containers:
      - name: udagram-frontend-api
        image: eedy/frontend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 2048Mi
            cpu: "500m"