apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend-api
  name: udagram-frontend-api
  
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 80
    
  selector:
    app: udagram-frontend-api